

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class LeadCompetitor : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the LeadCompetitor entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LeadCompetitor()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LeadCompetitor(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LeadCompetitor> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.LeadCompetitor.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeadCompetitor_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeadCompetitor_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid LeadCompetitorId
        {
            get
            {
                return global::LightSwitchApplication.LeadCompetitor.DetailsClass.GetValue(this, global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.LeadCompetitorId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeadCompetitorId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeadCompetitorId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeadCompetitorId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<long> VersionNumber
        {
            get
            {
                return global::LightSwitchApplication.LeadCompetitor.DetailsClass.GetValue(this, global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.VersionNumber);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VersionNumber_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VersionNumber_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VersionNumber_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Lead leadcompetitors_association_lead
        {
            get
            {
                return global::LightSwitchApplication.LeadCompetitor.DetailsClass.GetValue(this, global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.leadcompetitors_association_lead);
            }
            set
            {
                global::LightSwitchApplication.LeadCompetitor.DetailsClass.SetValue(this, global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.leadcompetitors_association_lead, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void leadcompetitors_association_lead_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void leadcompetitors_association_lead_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void leadcompetitors_association_lead_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Competitor leadcompetitors_association_competitor
        {
            get
            {
                return global::LightSwitchApplication.LeadCompetitor.DetailsClass.GetValue(this, global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.leadcompetitors_association_competitor);
            }
            set
            {
                global::LightSwitchApplication.LeadCompetitor.DetailsClass.SetValue(this, global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.leadcompetitors_association_competitor, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void leadcompetitors_association_competitor_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void leadcompetitors_association_competitor_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void leadcompetitors_association_competitor_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.LeadCompetitor,
                global::LightSwitchApplication.LeadCompetitor.DetailsClass,
                global::LightSwitchApplication.LeadCompetitor.DetailsClass.IImplementation,
                global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.LeadCompetitorId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass>.Entry
                __LeadCompetitorEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass>.Entry(
                    global::LightSwitchApplication.LeadCompetitor.DetailsClass.__LeadCompetitor_CreateNew,
                    global::LightSwitchApplication.LeadCompetitor.DetailsClass.__LeadCompetitor_Created,
                    global::LightSwitchApplication.LeadCompetitor.DetailsClass.__LeadCompetitor_AllowSaveWithErrors);
            private static global::LightSwitchApplication.LeadCompetitor __LeadCompetitor_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LeadCompetitor> es)
            {
                return new global::LightSwitchApplication.LeadCompetitor(es);
            }
            private static void __LeadCompetitor_Created(global::LightSwitchApplication.LeadCompetitor e)
            {
                e.LeadCompetitor_Created();
            }
            private static bool __LeadCompetitor_AllowSaveWithErrors(global::LightSwitchApplication.LeadCompetitor e)
            {
                bool result = false;
                e.LeadCompetitor_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::System.Guid> LeadCompetitorId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.LeadCompetitorId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::System.Nullable<long>> VersionNumber
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.VersionNumber) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::System.Nullable<long>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::LightSwitchApplication.Lead> leadcompetitors_association_lead
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.leadcompetitors_association_lead) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::LightSwitchApplication.Lead>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::LightSwitchApplication.Competitor> leadcompetitors_association_competitor
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.leadcompetitors_association_competitor) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::LightSwitchApplication.Competitor>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Guid LeadCompetitorId { get; }
                new global::System.Nullable<long> VersionNumber { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation leadcompetitors_association_lead { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation leadcompetitors_association_competitor { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::System.Guid>.Entry
                    LeadCompetitorId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::System.Guid>.Entry(
                        "LeadCompetitorId",
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._LeadCompetitorId_Stub,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._LeadCompetitorId_ComputeIsReadOnly,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._LeadCompetitorId_Validate,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._LeadCompetitorId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._LeadCompetitorId_OnValueChanged);
                private static void _LeadCompetitorId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.LeadCompetitor.DetailsClass d, object sf)
                {
                    c(d, ref d._LeadCompetitorId, sf);
                }
                private static bool _LeadCompetitorId_ComputeIsReadOnly(global::LightSwitchApplication.LeadCompetitor e)
                {
                    bool result = false;
                    e.LeadCompetitorId_IsReadOnly(ref result);
                    return result;
                }
                private static void _LeadCompetitorId_Validate(global::LightSwitchApplication.LeadCompetitor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LeadCompetitorId_Validate(r);
                }
                private static global::System.Guid _LeadCompetitorId_GetImplementationValue(global::LightSwitchApplication.LeadCompetitor.DetailsClass d)
                {
                    return d.ImplementationEntity.LeadCompetitorId;
                }
                private static void _LeadCompetitorId_OnValueChanged(global::LightSwitchApplication.LeadCompetitor e)
                {
                    e.LeadCompetitorId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::System.Nullable<long>>.Entry
                    VersionNumber = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::System.Nullable<long>>.Entry(
                        "VersionNumber",
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._VersionNumber_Stub,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._VersionNumber_ComputeIsReadOnly,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._VersionNumber_Validate,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._VersionNumber_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._VersionNumber_OnValueChanged);
                private static void _VersionNumber_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::System.Nullable<long>>.Data> c, global::LightSwitchApplication.LeadCompetitor.DetailsClass d, object sf)
                {
                    c(d, ref d._VersionNumber, sf);
                }
                private static bool _VersionNumber_ComputeIsReadOnly(global::LightSwitchApplication.LeadCompetitor e)
                {
                    bool result = false;
                    e.VersionNumber_IsReadOnly(ref result);
                    return result;
                }
                private static void _VersionNumber_Validate(global::LightSwitchApplication.LeadCompetitor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.VersionNumber_Validate(r);
                }
                private static global::System.Nullable<long> _VersionNumber_GetImplementationValue(global::LightSwitchApplication.LeadCompetitor.DetailsClass d)
                {
                    return d.ImplementationEntity.VersionNumber;
                }
                private static void _VersionNumber_OnValueChanged(global::LightSwitchApplication.LeadCompetitor e)
                {
                    e.VersionNumber_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::LightSwitchApplication.Lead>.Entry
                    leadcompetitors_association_lead = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::LightSwitchApplication.Lead>.Entry(
                        "leadcompetitors_association_lead",
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_lead_Stub,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_lead_ComputeIsReadOnly,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_lead_Validate,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_lead_GetCoreImplementationValue,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_lead_GetImplementationValue,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_lead_SetImplementationValue,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_lead_Refresh,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_lead_OnValueChanged);
                private static void _leadcompetitors_association_lead_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::LightSwitchApplication.Lead>.Data> c, global::LightSwitchApplication.LeadCompetitor.DetailsClass d, object sf)
                {
                    c(d, ref d._leadcompetitors_association_lead, sf);
                }
                private static bool _leadcompetitors_association_lead_ComputeIsReadOnly(global::LightSwitchApplication.LeadCompetitor e)
                {
                    bool result = false;
                    e.leadcompetitors_association_lead_IsReadOnly(ref result);
                    return result;
                }
                private static void _leadcompetitors_association_lead_Validate(global::LightSwitchApplication.LeadCompetitor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.leadcompetitors_association_lead_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _leadcompetitors_association_lead_GetCoreImplementationValue(global::LightSwitchApplication.LeadCompetitor.DetailsClass d)
                {
                    return d.ImplementationEntity.leadcompetitors_association_lead;
                }
                private static global::LightSwitchApplication.Lead _leadcompetitors_association_lead_GetImplementationValue(global::LightSwitchApplication.LeadCompetitor.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Lead, global::LightSwitchApplication.Lead.DetailsClass>(global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.leadcompetitors_association_lead, ref d._leadcompetitors_association_lead);
                }
                private static void _leadcompetitors_association_lead_SetImplementationValue(global::LightSwitchApplication.LeadCompetitor.DetailsClass d, global::LightSwitchApplication.Lead v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.leadcompetitors_association_lead, ref d._leadcompetitors_association_lead, (i, ev) => i.leadcompetitors_association_lead = ev, v);
                }
                private static void _leadcompetitors_association_lead_Refresh(global::LightSwitchApplication.LeadCompetitor.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.leadcompetitors_association_lead, ref d._leadcompetitors_association_lead);
                }
                private static void _leadcompetitors_association_lead_OnValueChanged(global::LightSwitchApplication.LeadCompetitor e)
                {
                    e.leadcompetitors_association_lead_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::LightSwitchApplication.Competitor>.Entry
                    leadcompetitors_association_competitor = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::LightSwitchApplication.Competitor>.Entry(
                        "leadcompetitors_association_competitor",
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_competitor_Stub,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_competitor_ComputeIsReadOnly,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_competitor_Validate,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_competitor_GetCoreImplementationValue,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_competitor_GetImplementationValue,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_competitor_SetImplementationValue,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_competitor_Refresh,
                        global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties._leadcompetitors_association_competitor_OnValueChanged);
                private static void _leadcompetitors_association_competitor_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::LightSwitchApplication.Competitor>.Data> c, global::LightSwitchApplication.LeadCompetitor.DetailsClass d, object sf)
                {
                    c(d, ref d._leadcompetitors_association_competitor, sf);
                }
                private static bool _leadcompetitors_association_competitor_ComputeIsReadOnly(global::LightSwitchApplication.LeadCompetitor e)
                {
                    bool result = false;
                    e.leadcompetitors_association_competitor_IsReadOnly(ref result);
                    return result;
                }
                private static void _leadcompetitors_association_competitor_Validate(global::LightSwitchApplication.LeadCompetitor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.leadcompetitors_association_competitor_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _leadcompetitors_association_competitor_GetCoreImplementationValue(global::LightSwitchApplication.LeadCompetitor.DetailsClass d)
                {
                    return d.ImplementationEntity.leadcompetitors_association_competitor;
                }
                private static global::LightSwitchApplication.Competitor _leadcompetitors_association_competitor_GetImplementationValue(global::LightSwitchApplication.LeadCompetitor.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Competitor, global::LightSwitchApplication.Competitor.DetailsClass>(global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.leadcompetitors_association_competitor, ref d._leadcompetitors_association_competitor);
                }
                private static void _leadcompetitors_association_competitor_SetImplementationValue(global::LightSwitchApplication.LeadCompetitor.DetailsClass d, global::LightSwitchApplication.Competitor v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.leadcompetitors_association_competitor, ref d._leadcompetitors_association_competitor, (i, ev) => i.leadcompetitors_association_competitor = ev, v);
                }
                private static void _leadcompetitors_association_competitor_Refresh(global::LightSwitchApplication.LeadCompetitor.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.LeadCompetitor.DetailsClass.PropertySetProperties.leadcompetitors_association_competitor, ref d._leadcompetitors_association_competitor);
                }
                private static void _leadcompetitors_association_competitor_OnValueChanged(global::LightSwitchApplication.LeadCompetitor e)
                {
                    e.leadcompetitors_association_competitor_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::System.Guid>.Data _LeadCompetitorId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::System.Nullable<long>>.Data _VersionNumber;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::LightSwitchApplication.Lead>.Data _leadcompetitors_association_lead;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadCompetitor, global::LightSwitchApplication.LeadCompetitor.DetailsClass, global::LightSwitchApplication.Competitor>.Data _leadcompetitors_association_competitor;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class LeadProduct : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the LeadProduct entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LeadProduct()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LeadProduct(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LeadProduct> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.LeadProduct.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeadProduct_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeadProduct_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid LeadProductId
        {
            get
            {
                return global::LightSwitchApplication.LeadProduct.DetailsClass.GetValue(this, global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.LeadProductId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeadProductId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeadProductId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LeadProductId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<long> VersionNumber
        {
            get
            {
                return global::LightSwitchApplication.LeadProduct.DetailsClass.GetValue(this, global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.VersionNumber);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VersionNumber_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VersionNumber_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VersionNumber_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Lead leadproduct_association_lead
        {
            get
            {
                return global::LightSwitchApplication.LeadProduct.DetailsClass.GetValue(this, global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.leadproduct_association_lead);
            }
            set
            {
                global::LightSwitchApplication.LeadProduct.DetailsClass.SetValue(this, global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.leadproduct_association_lead, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void leadproduct_association_lead_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void leadproduct_association_lead_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void leadproduct_association_lead_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Product leadproduct_association_product
        {
            get
            {
                return global::LightSwitchApplication.LeadProduct.DetailsClass.GetValue(this, global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.leadproduct_association_product);
            }
            set
            {
                global::LightSwitchApplication.LeadProduct.DetailsClass.SetValue(this, global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.leadproduct_association_product, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void leadproduct_association_product_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void leadproduct_association_product_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void leadproduct_association_product_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.LeadProduct,
                global::LightSwitchApplication.LeadProduct.DetailsClass,
                global::LightSwitchApplication.LeadProduct.DetailsClass.IImplementation,
                global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.LeadProductId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass>.Entry
                __LeadProductEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass>.Entry(
                    global::LightSwitchApplication.LeadProduct.DetailsClass.__LeadProduct_CreateNew,
                    global::LightSwitchApplication.LeadProduct.DetailsClass.__LeadProduct_Created,
                    global::LightSwitchApplication.LeadProduct.DetailsClass.__LeadProduct_AllowSaveWithErrors);
            private static global::LightSwitchApplication.LeadProduct __LeadProduct_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LeadProduct> es)
            {
                return new global::LightSwitchApplication.LeadProduct(es);
            }
            private static void __LeadProduct_Created(global::LightSwitchApplication.LeadProduct e)
            {
                e.LeadProduct_Created();
            }
            private static bool __LeadProduct_AllowSaveWithErrors(global::LightSwitchApplication.LeadProduct e)
            {
                bool result = false;
                e.LeadProduct_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::System.Guid> LeadProductId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.LeadProductId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::System.Nullable<long>> VersionNumber
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.VersionNumber) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::System.Nullable<long>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::LightSwitchApplication.Lead> leadproduct_association_lead
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.leadproduct_association_lead) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::LightSwitchApplication.Lead>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::LightSwitchApplication.Product> leadproduct_association_product
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.leadproduct_association_product) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::LightSwitchApplication.Product>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Guid LeadProductId { get; }
                new global::System.Nullable<long> VersionNumber { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation leadproduct_association_lead { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation leadproduct_association_product { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::System.Guid>.Entry
                    LeadProductId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::System.Guid>.Entry(
                        "LeadProductId",
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._LeadProductId_Stub,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._LeadProductId_ComputeIsReadOnly,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._LeadProductId_Validate,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._LeadProductId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._LeadProductId_OnValueChanged);
                private static void _LeadProductId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LeadProduct.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.LeadProduct.DetailsClass d, object sf)
                {
                    c(d, ref d._LeadProductId, sf);
                }
                private static bool _LeadProductId_ComputeIsReadOnly(global::LightSwitchApplication.LeadProduct e)
                {
                    bool result = false;
                    e.LeadProductId_IsReadOnly(ref result);
                    return result;
                }
                private static void _LeadProductId_Validate(global::LightSwitchApplication.LeadProduct e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LeadProductId_Validate(r);
                }
                private static global::System.Guid _LeadProductId_GetImplementationValue(global::LightSwitchApplication.LeadProduct.DetailsClass d)
                {
                    return d.ImplementationEntity.LeadProductId;
                }
                private static void _LeadProductId_OnValueChanged(global::LightSwitchApplication.LeadProduct e)
                {
                    e.LeadProductId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::System.Nullable<long>>.Entry
                    VersionNumber = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::System.Nullable<long>>.Entry(
                        "VersionNumber",
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._VersionNumber_Stub,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._VersionNumber_ComputeIsReadOnly,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._VersionNumber_Validate,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._VersionNumber_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._VersionNumber_OnValueChanged);
                private static void _VersionNumber_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LeadProduct.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::System.Nullable<long>>.Data> c, global::LightSwitchApplication.LeadProduct.DetailsClass d, object sf)
                {
                    c(d, ref d._VersionNumber, sf);
                }
                private static bool _VersionNumber_ComputeIsReadOnly(global::LightSwitchApplication.LeadProduct e)
                {
                    bool result = false;
                    e.VersionNumber_IsReadOnly(ref result);
                    return result;
                }
                private static void _VersionNumber_Validate(global::LightSwitchApplication.LeadProduct e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.VersionNumber_Validate(r);
                }
                private static global::System.Nullable<long> _VersionNumber_GetImplementationValue(global::LightSwitchApplication.LeadProduct.DetailsClass d)
                {
                    return d.ImplementationEntity.VersionNumber;
                }
                private static void _VersionNumber_OnValueChanged(global::LightSwitchApplication.LeadProduct e)
                {
                    e.VersionNumber_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::LightSwitchApplication.Lead>.Entry
                    leadproduct_association_lead = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::LightSwitchApplication.Lead>.Entry(
                        "leadproduct_association_lead",
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_lead_Stub,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_lead_ComputeIsReadOnly,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_lead_Validate,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_lead_GetCoreImplementationValue,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_lead_GetImplementationValue,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_lead_SetImplementationValue,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_lead_Refresh,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_lead_OnValueChanged);
                private static void _leadproduct_association_lead_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LeadProduct.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::LightSwitchApplication.Lead>.Data> c, global::LightSwitchApplication.LeadProduct.DetailsClass d, object sf)
                {
                    c(d, ref d._leadproduct_association_lead, sf);
                }
                private static bool _leadproduct_association_lead_ComputeIsReadOnly(global::LightSwitchApplication.LeadProduct e)
                {
                    bool result = false;
                    e.leadproduct_association_lead_IsReadOnly(ref result);
                    return result;
                }
                private static void _leadproduct_association_lead_Validate(global::LightSwitchApplication.LeadProduct e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.leadproduct_association_lead_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _leadproduct_association_lead_GetCoreImplementationValue(global::LightSwitchApplication.LeadProduct.DetailsClass d)
                {
                    return d.ImplementationEntity.leadproduct_association_lead;
                }
                private static global::LightSwitchApplication.Lead _leadproduct_association_lead_GetImplementationValue(global::LightSwitchApplication.LeadProduct.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Lead, global::LightSwitchApplication.Lead.DetailsClass>(global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.leadproduct_association_lead, ref d._leadproduct_association_lead);
                }
                private static void _leadproduct_association_lead_SetImplementationValue(global::LightSwitchApplication.LeadProduct.DetailsClass d, global::LightSwitchApplication.Lead v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.leadproduct_association_lead, ref d._leadproduct_association_lead, (i, ev) => i.leadproduct_association_lead = ev, v);
                }
                private static void _leadproduct_association_lead_Refresh(global::LightSwitchApplication.LeadProduct.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.leadproduct_association_lead, ref d._leadproduct_association_lead);
                }
                private static void _leadproduct_association_lead_OnValueChanged(global::LightSwitchApplication.LeadProduct e)
                {
                    e.leadproduct_association_lead_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::LightSwitchApplication.Product>.Entry
                    leadproduct_association_product = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::LightSwitchApplication.Product>.Entry(
                        "leadproduct_association_product",
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_product_Stub,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_product_ComputeIsReadOnly,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_product_Validate,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_product_GetCoreImplementationValue,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_product_GetImplementationValue,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_product_SetImplementationValue,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_product_Refresh,
                        global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties._leadproduct_association_product_OnValueChanged);
                private static void _leadproduct_association_product_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LeadProduct.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::LightSwitchApplication.Product>.Data> c, global::LightSwitchApplication.LeadProduct.DetailsClass d, object sf)
                {
                    c(d, ref d._leadproduct_association_product, sf);
                }
                private static bool _leadproduct_association_product_ComputeIsReadOnly(global::LightSwitchApplication.LeadProduct e)
                {
                    bool result = false;
                    e.leadproduct_association_product_IsReadOnly(ref result);
                    return result;
                }
                private static void _leadproduct_association_product_Validate(global::LightSwitchApplication.LeadProduct e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.leadproduct_association_product_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _leadproduct_association_product_GetCoreImplementationValue(global::LightSwitchApplication.LeadProduct.DetailsClass d)
                {
                    return d.ImplementationEntity.leadproduct_association_product;
                }
                private static global::LightSwitchApplication.Product _leadproduct_association_product_GetImplementationValue(global::LightSwitchApplication.LeadProduct.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>(global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.leadproduct_association_product, ref d._leadproduct_association_product);
                }
                private static void _leadproduct_association_product_SetImplementationValue(global::LightSwitchApplication.LeadProduct.DetailsClass d, global::LightSwitchApplication.Product v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.leadproduct_association_product, ref d._leadproduct_association_product, (i, ev) => i.leadproduct_association_product = ev, v);
                }
                private static void _leadproduct_association_product_Refresh(global::LightSwitchApplication.LeadProduct.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.LeadProduct.DetailsClass.PropertySetProperties.leadproduct_association_product, ref d._leadproduct_association_product);
                }
                private static void _leadproduct_association_product_OnValueChanged(global::LightSwitchApplication.LeadProduct e)
                {
                    e.leadproduct_association_product_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::System.Guid>.Data _LeadProductId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::System.Nullable<long>>.Data _VersionNumber;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::LightSwitchApplication.Lead>.Data _leadproduct_association_lead;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LeadProduct, global::LightSwitchApplication.LeadProduct.DetailsClass, global::LightSwitchApplication.Product>.Data _leadproduct_association_product;
            
        }
    
        #endregion
    }
    
    #endregion
}
